sudo: required
language: node_js
node_js:
  - 16

services:
  - docker
before install:
  - docker build -t wilsonzhang911/sample-app -f Dockerfile.dev .
  - docker push wilsonzhang911/sample-app
script:
  - docker run -e CI=true wilsonzhang911/sample-app npm run test -- --coverage --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "sample-docker-react"
  env: "Sampledockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-011957927785"
  bucket_path: "EBApptest"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
